#!/bin/sh

# Copyright (C) 2017 openwrt-ssr
# Copyright (C) 2017 yushi studio <ywb94@qq.com>
# Copyright (C) 2019 chongshengB
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

cycle_time=10
switch_time=3
current_ret=1
[ -n "$2" ] && cycle_time=$2
[ -n "$3" ] && switch_time=$3

DEFAULT_SERVER=$(nvram get global_server)
CURRENT_SERVER=$DEFAULT_SERVER
BACKUP_SERVER=$(nvram get backup_server)

check_proxy() {
  result=0
  for i in $(seq 1 3)
  do
	/usr/bin/ss-check www.facebook.com 80 $switch_time 1
	if [ "$?" == "0" ]; then
		result=0
	    	echo "$(date "+%Y-%m-%d %H:%M:%S") ${CURRENT_SERVER}号服务器已连接,检测方式:facebook" >> /tmp/ssrplus.log
		break
	fi

	/usr/bin/ss-check www.youtube.com 80 $switch_time 1
	if [ "$?" == "0" ]; then
		result=0
	   	echo "$(date "+%Y-%m-%d %H:%M:%S") ${CURRENT_SERVER}号服务器已连接,检测方式:youtube" >> /tmp/ssrplus.log
		break
	fi
	/usr/bin/ss-check www.google.com 80 $switch_time 1
	if [ "$?" == "0" ]; then
		result=0
	   	echo "$(date "+%Y-%m-%d %H:%M:%S") ${CURRENT_SERVER}号服务器已连接,检测方式:google" >> /tmp/ssrplus.log
		break
	fi

	/usr/bin/ss-check www.baidu.com 80 $switch_time 1
	if [ "$?" == "0" ]; then
		result=1
		echo "$(date "+%Y-%m-%d %H:%M:%S") ${CURRENT_SERVER}号服务器连接失败, 检测次数=$i，3次后自动切换。" >> /tmp/ssrplus.log
		
	else
		result=2
		echo "$(date "+%Y-%m-%d %H:%M:%S") 网络连接失败, 检测次数=$i，3次后自动切换。" >> /tmp/ssrplus.log
		
	fi
    	sleep ${switch_time}s
  done
  current_ret=$result;
}

a_start() {
while [ "1" = "1" ]  #死循环
do
	sleep $cycle_time
	check_proxy
    	current_ret = $?
	echo "current_ret：${current_ret} " >> /tmp/ssrplus.log
	if [ "$current_ret" = 1 ] ;then
	#当前代理错误，判断有无可用的服务器
		if [ $(nvram get check_mode) = "1" ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") 所有服务器挂掉了,重新循环切换,如需停止,请手动关闭看看世界！" >> /tmp/ssrplus.log
			###nvram set ss_enable=0
			nvram set check_mode=0
			###/usr/bin/shadowsocks.sh stop &
			###exit 0
		else
			nvram set check_mode=1
		fi
		echo "$(date "+%Y-%m-%d %H:%M:%S") 检测到${CURRENT_SERVER}号服务器故障，切换到${BACKUP_SERVER}号服务器。" >> /tmp/ssrplus.log
		/usr/bin/shadowsocks.sh stop &
		###nvram set check_mode=1 #停止标记
		/usr/bin/shadowsocks.sh reserver &
	fi
done
}

case $1 in
start)
	a_start
	;;
stop)
	a_close
	;;
esac
